name: Verify

# trigger on push to branches and PR
on:
  push:
    branches:
    - '**'        # matches every branch
    tags:
    - 'project-settings-extension-[0-9]+'
    - 'project-settings-extension-[0-9]+.[0-9]+'
    - 'project-settings-extension-[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  build:
    name: 'with JDK ${{ matrix.jdk }}'
    strategy:
      fail-fast: false
      matrix:
        jdk: [ 11, 17 ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '${{ matrix.jdk }}'
          distribution: 'temurin'
          cache: maven

      - name: Build and verify
        run: ./mvnw verify --batch-mode --no-transfer-progress --errors

  release-on-tag:
    name: 'Publish tag ${{ github.ref_name }} to the Maven Central Repository'
    needs: build
    if: github.repository == 'gzm55/project-settings-maven-extension' && startsWith(github.ref, 'refs/tags/project-settings-extension-')
    # ref_protected is not set to true for protected tags now
    # ref: https://github.com/orgs/community/discussions/10906#discussioncomment-3915816
    runs-on: ubuntu-latest
    environment:
      name: Maven Publish
      url: https://oss.sonatype.org/

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

      - name: Dump Settings
        run: |
          gpg --list-keys
          env
          ./mvnw -V -B help:effective-settings -gs .cd/settings.xml

      - name: Publish package
        run: ./mvnw -B -DskipTests -Dinvoker.skip -gs .cd/settings.xml -P release-profile deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
